//! Vector commitment built directly on the KZG10 scheme from
//! `ark-poly-commit` (https://github.com/arkworks-rs/poly-commit) — this
//! module contributes no polynomial-commitment cryptography of its own, only
//! the glue to use that crate as a vector commitment.
//!
//! A vector (m_0, ..., m_{d-1}) is interpolated into the polynomial p with
//! p(w^i) = m_i over the radix-2 evaluation domain of size
//! `width.next_power_of_two()` (w a root of unity), and committed via
//! `kzg10::KZG10::commit`. "Opening slot i" is exactly a standard KZG10
//! single-point evaluation proof at w^i, produced by `kzg10::KZG10::open`
//! and checked by `kzg10::KZG10::check`.
//!
//! The SRS (powers of tau) is generated by `KZG10::setup` fed with an RNG
//! seeded from a hard-coded label, i.e. tau is knowable and the setup is
//! INSECURE. It stands in for a real powers-of-tau ceremony; the setup
//! algorithm itself is the library's.

use crate::vc::VectorCommitment;
use ark_bls12_381::{Bls12_381, Fr};
use ark_poly::{univariate::DensePolynomial, DenseUVPolynomial, EvaluationDomain, Radix2EvaluationDomain};
use ark_poly_commit::kzg10::{Powers, VerifierKey, KZG10};
use ark_poly_commit::{PCCommitment, PCCommitmentState};
use ark_serialize::CanonicalSerialize;
use ark_std::rand::{rngs::StdRng, SeedableRng};
use sha2::{Digest as _, Sha256};
use std::borrow::Cow;

type UniPoly = DensePolynomial<Fr>;
type Scheme = KZG10<Bls12_381, UniPoly>;
type SchemeRandomness = ark_poly_commit::kzg10::Randomness<Fr, UniPoly>;

pub struct KzgVc {
    domain: Radix2EvaluationDomain<Fr>,
    powers: Powers<'static, Bls12_381>,
    vk: VerifierKey<Bls12_381>,
}

impl KzgVc {
    fn interpolate(&self, values: &[Fr]) -> UniPoly {
        assert!(values.len() <= self.domain.size());
        let mut evals = values.to_vec();
        evals.resize(self.domain.size(), Fr::from(0u64));
        UniPoly::from_coefficients_vec(self.domain.ifft(&evals))
    }
}

impl VectorCommitment for KzgVc {
    type Field = Fr;
    type Commitment = ark_poly_commit::kzg10::Commitment<Bls12_381>;
    type Witness = ark_poly_commit::kzg10::Proof<Bls12_381>;
    /// The interpolated polynomial: opening never re-interpolates, though it
    /// still commits to the quotient polynomial (inherent to KZG openings).
    type Opener = UniPoly;

    /// Demo only: tau is derived from a public seed, so the setup is
    /// INSECURE (see module doc).
    fn setup(width: usize) -> Self {
        let size = width.next_power_of_two();
        let seed32: [u8; 32] = Sha256::digest(b"IBSL demo trusted setup").into();
        let mut rng = StdRng::from_seed(seed32);
        // No G2 powers needed: we only ever do single-point openings.
        let pp = Scheme::setup(size, false, &mut rng).expect("KZG10 setup");

        let powers_of_g = pp.powers_of_g[..size].to_vec();
        let powers_of_gamma_g = (0..size).map(|i| pp.powers_of_gamma_g[&i]).collect();
        let powers = Powers {
            powers_of_g: Cow::Owned(powers_of_g),
            powers_of_gamma_g: Cow::Owned(powers_of_gamma_g),
        };
        let vk = VerifierKey {
            g: pp.powers_of_g[0],
            gamma_g: pp.powers_of_gamma_g[&0],
            h: pp.h,
            beta_h: pp.beta_h,
            prepared_h: pp.prepared_h.clone(),
            prepared_beta_h: pp.prepared_beta_h.clone(),
        };

        KzgVc {
            domain: Radix2EvaluationDomain::new(size).expect("radix-2 domain"),
            powers,
            vk,
        }
    }

    fn empty_commitment() -> Self::Commitment {
        Self::Commitment::empty()
    }

    /// Non-hiding: KZG10 with no hiding bound.
    fn commit(&self, values: &[Fr]) -> (Self::Commitment, Self::Opener) {
        let p = self.interpolate(values);
        let c = Scheme::commit(&self.powers, &p, None, None).expect("commit").0;
        (c, p)
    }

    fn open(&self, p: &Self::Opener, i: usize) -> Self::Witness {
        Scheme::open(&self.powers, p, self.domain.element(i), &SchemeRandomness::empty())
            .expect("open")
    }

    fn check(&self, c: &Self::Commitment, i: usize, value: Fr, w: &Self::Witness) -> bool {
        if i >= self.domain.size() {
            return false;
        }
        Scheme::check(&self.vk, c, self.domain.element(i), value, w).unwrap_or(false)
    }

    fn commitment_bytes(c: &Self::Commitment) -> Vec<u8> {
        let mut bytes = Vec::new();
        c.serialize_compressed(&mut bytes).expect("serialization");
        bytes
    }

    /// Group element -> Fr via SHA-256 of its canonical bytes.
    fn to_field(c: &Self::Commitment) -> Fr {
        use ark_ff::PrimeField;
        Fr::from_le_bytes_mod_order(&Sha256::digest(Self::commitment_bytes(c)))
    }
}
