//! Vector commitment built directly on the KZG10 scheme from
//! `ark-poly-commit` (https://github.com/arkworks-rs/poly-commit) — this
//! module contributes no polynomial-commitment cryptography of its own, only
//! the glue to use that crate as a vector commitment.
//!
//! A vector (m_0, ..., m_{d-1}), d <= WIDTH, is interpolated into the
//! polynomial p with p(w^i) = m_i over the radix-2 evaluation domain of size
//! WIDTH (w a WIDTH-th root of unity), and committed via
//! `kzg10::KZG10::commit`. "Opening slot i" is exactly a standard KZG10
//! single-point evaluation proof at w^i, produced by `kzg10::KZG10::open`
//! and checked by `kzg10::KZG10::check`.
//!
//! The SRS (powers of tau) is generated by `KZG10::setup` fed with an RNG
//! seeded from a hard-coded label, i.e. tau is knowable and the setup is
//! INSECURE. It stands in for a real powers-of-tau ceremony; the setup
//! algorithm itself is the library's. The SRS is universal: one setup serves
//! every IBSL instance, which is why it lives in a global.

use ark_bls12_381::{Bls12_381, Fr};
use ark_poly::{univariate::DensePolynomial, DenseUVPolynomial, EvaluationDomain, Radix2EvaluationDomain};
use ark_poly_commit::kzg10::{Powers, VerifierKey, KZG10};
use ark_poly_commit::PCCommitmentState;
use ark_serialize::CanonicalSerialize;
use ark_std::rand::{rngs::StdRng, SeedableRng};
use sha2::{Digest as _, Sha256};
use std::borrow::Cow;
use std::sync::OnceLock;

/// Size of the evaluation domain, i.e. the maximum committed vector length.
pub const WIDTH: usize = 8;

type UniPoly = DensePolynomial<Fr>;
type Scheme = KZG10<Bls12_381, UniPoly>;
type SchemeRandomness = ark_poly_commit::kzg10::Randomness<Fr, UniPoly>;

pub type Commitment = ark_poly_commit::kzg10::Commitment<Bls12_381>;
pub type Witness = ark_poly_commit::kzg10::Proof<Bls12_381>;

pub struct KzgParams {
    domain: Radix2EvaluationDomain<Fr>,
    powers: Powers<'static, Bls12_381>,
    vk: VerifierKey<Bls12_381>,
}

/// The global (universal) SRS. Demo only: tau is derived from a public seed.
pub fn params() -> &'static KzgParams {
    static PARAMS: OnceLock<KzgParams> = OnceLock::new();
    PARAMS.get_or_init(|| KzgParams::insecure_setup(b"IBSL demo trusted setup"))
}

/// Maps a child commitment into Fr so it can be a slot of the parent's
/// vector (an absent child is encoded as 0 directly, without hashing).
pub fn commitment_to_field(c: &Commitment) -> Fr {
    use ark_ff::PrimeField;
    let mut bytes = Vec::new();
    c.serialize_compressed(&mut bytes).expect("serialization");
    Fr::from_le_bytes_mod_order(&Sha256::digest(&bytes))
}

impl KzgParams {
    fn insecure_setup(seed: &[u8]) -> Self {
        let seed32: [u8; 32] = Sha256::digest(seed).into();
        let mut rng = StdRng::from_seed(seed32);
        // No G2 powers needed: we only ever do single-point openings.
        let pp = Scheme::setup(WIDTH, false, &mut rng).expect("KZG10 setup");

        let powers_of_g = pp.powers_of_g[..WIDTH].to_vec();
        let powers_of_gamma_g = (0..WIDTH).map(|i| pp.powers_of_gamma_g[&i]).collect();
        let powers = Powers {
            powers_of_g: Cow::Owned(powers_of_g),
            powers_of_gamma_g: Cow::Owned(powers_of_gamma_g),
        };
        let vk = VerifierKey {
            g: pp.powers_of_g[0],
            gamma_g: pp.powers_of_gamma_g[&0],
            h: pp.h,
            beta_h: pp.beta_h,
            prepared_h: pp.prepared_h.clone(),
            prepared_beta_h: pp.prepared_beta_h.clone(),
        };

        KzgParams {
            domain: Radix2EvaluationDomain::new(WIDTH).expect("domain of size WIDTH"),
            powers,
            vk,
        }
    }

    fn interpolate(&self, values: &[Fr]) -> UniPoly {
        assert!(values.len() <= WIDTH);
        let mut evals = values.to_vec();
        evals.resize(WIDTH, Fr::from(0u64));
        UniPoly::from_coefficients_vec(self.domain.ifft(&evals))
    }

    /// C = Com(m_0, ..., m_{d-1}). Non-hiding: KZG10 with no hiding bound.
    pub fn commit(&self, values: &[Fr]) -> Commitment {
        let p = self.interpolate(values);
        Scheme::commit(&self.powers, &p, None, None).expect("commit").0
    }

    /// Standard KZG10 evaluation proof that slot `i` of the vector holds
    /// `values[i]`.
    pub fn open(&self, values: &[Fr], i: usize) -> Witness {
        let p = self.interpolate(values);
        Scheme::open(&self.powers, &p, self.domain.element(i), &SchemeRandomness::empty())
            .expect("open")
    }

    /// Verifies a single-slot KZG10 opening against commitment `c`.
    pub fn check(&self, c: &Commitment, i: usize, value: Fr, w: &Witness) -> bool {
        if i >= WIDTH {
            return false;
        }
        Scheme::check(&self.vk, c, self.domain.element(i), value, w).unwrap_or(false)
    }
}
